#!/bin/bash
# Generate docker-compose.users.yml for user frontend containers
# Uses NUM_USERS from .env (default: 20)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_FILE="$PROJECT_DIR/docker-compose.users.yml"

# Load NUM_USERS from .env if it exists
if [ -f "$PROJECT_DIR/.env" ]; then
    source "$PROJECT_DIR/.env"
fi
NUM_USERS="${NUM_USERS:-20}"

echo "Generating docker-compose.users.yml for $NUM_USERS users..."

cat > "$OUTPUT_FILE" << 'HEADER'
# Auto-generated user frontend services
# Generated by: scripts/generate-user-compose.sh
# DO NOT EDIT MANUALLY - regenerate with: ./scripts/generate-user-compose.sh

services:
HEADER

# Generate service for each user
for i in $(seq 1 $NUM_USERS); do
    USER_ID=$(printf "user%03d" $i)
    PORT=$((8187 + i))  # user001 = 8188, user002 = 8189, etc.

    cat >> "$OUTPUT_FILE" << EOF
  $USER_ID:
    build:
      context: ./comfyui-frontend
      dockerfile: Dockerfile
    container_name: comfy-$USER_ID
    ports:
      - "127.0.0.1:$PORT:8188"
    environment:
      - USER_ID=$USER_ID
      - QUEUE_MANAGER_URL=http://queue-manager:3000
    volumes:
      - \${OUTPUTS_PATH}:/outputs
      - \${INPUTS_PATH}:/inputs
      - \${WORKFLOWS_PATH}:/workflows:ro
      - \${MODELS_PATH}:/models:ro
      - ./data/user_data/$USER_ID:/comfyui/user
    networks:
      - comfy-network
    restart: unless-stopped
    cpus: 1.0
    mem_limit: 2G

EOF
done

echo "✅ Generated $OUTPUT_FILE with $NUM_USERS user services"
echo ""
echo "To use: docker compose up -d"
echo "Note: docker-compose.yml includes this file automatically"
